/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package mixed

import clojure.java.api.Clojure

import scala.language.postfixOps

class ScalaSome {
  var thing = "ScalaSomeThing"

  def javaPureSome(javaPureSome: JavaPureSome): JavaPureSome = {
    javaPureSome.setThing(javaPureSome.getThing + "Scala");
    return javaPureSome;
  }
}

object App {

  var app = "app"

  def main(args: Array[String]): Unit = {
    println(greeting())

    val scaleSome = new ScalaSome()
    println("ScalaSome: scaleSome: " + scaleSome.thing)

    val javaPureSome = new JavaPureSome()
    println("ScalaSome: javaPureSome: " + javaPureSome.getThing)

    val javaSome = new JavaSome(scaleSome)
    println("ScalaSome: javaSome: " + javaSome.thing)

    println("Clojure: plus: " + Clojure.`var`("clojure.core", "+").invoke(1,2))

    // println("Clojure: " + Clojure.`var`("mixed", "buy-coffee").invoke(1, 2))

  }

  def greeting(): String = "Hello, world!"
}
