/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package mixed

import scala.language.postfixOps

class ScalaSome {
  var thing = "ScalaSomeThing"
}

object App {

  var app = "app"

  def main(args: Array[String]): Unit = {
    println(greeting())

    val scaleSome = new ScalaSome()
    println("ScalaSome: scaleSome: " + scaleSome.thing)

    val javaSome = new JavaSome()
    println("ScalaSome: javaSome: " + javaSome.thing)
  }

  def greeting(): String = "Hello, world!"
}
